/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Main.Dashboard;
import Services.connector;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LOQ
 */
public class FormLogin extends javax.swing.JFrame {
    public static String userId = "";

    /**
     * Creates new form FormLogin
     */
    int xx, xy;
    public FormLogin() {
        initComponents();
        
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustom2 = new Custom.PanelCustom();
        lb_showPassword = new javax.swing.JLabel();
        lb_hidePassword = new javax.swing.JLabel();
        loginHeading = new javax.swing.JLabel();
        loginDescription = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        btnLogin = new Custom.JButtonRounded();
        inputEmail = new Custom.JTextFieldRounded();
        inputPassword = new Custom.JPasswordFieldRounded();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCustom1 = new Custom.PanelCustom();
        loginImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setRequestFocusEnabled(false);
        panelCustom2.setRoundBottomLeft(20);
        panelCustom2.setRoundBottomRight(20);
        panelCustom2.setRoundTopLeft(20);
        panelCustom2.setRoundTopRight(20);
        panelCustom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye.png"))); // NOI18N
        lb_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showPasswordMouseClicked(evt);
            }
        });
        panelCustom2.add(lb_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 40, 40));

        lb_hidePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye-off (1).png"))); // NOI18N
        lb_hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hidePasswordMouseClicked(evt);
            }
        });
        panelCustom2.add(lb_hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 40, 40));

        loginHeading.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 28)); // NOI18N
        loginHeading.setForeground(new java.awt.Color(30, 30, 30));
        loginHeading.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginHeading.setText("Login ke Akun Anda");
        panelCustom2.add(loginHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 111, 310, 46));

        loginDescription.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        loginDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginDescription.setText("Selamat datang! Silahkan login terlebih dahulu.");
        panelCustom2.add(loginDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 167, -1, -1));

        EmailLabel.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        EmailLabel.setText("Email");
        panelCustom2.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 221, 309, -1));

        PasswordLabel.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        PasswordLabel.setText("Kata Sandi");
        panelCustom2.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 302, 309, -1));

        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        btnLogin.setStrokeWidth(0);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        panelCustom2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 378, 310, 40));

        inputEmail.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        inputEmail.setPreferredSize(new java.awt.Dimension(310, 40));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        panelCustom2.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, -1, -1));

        inputPassword.setPreferredSize(new java.awt.Dimension(310, 40));
        panelCustom2.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 104, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Daftar disini");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelCustom2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 433, 80, -1));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Belum punya akun?");
        panelCustom2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 433, 120, -1));

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setRoundBottomRight(20);
        panelCustom1.setRoundTopRight(20);

        loginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-img_1@4x.png"))); // NOI18N

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustom1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(loginImage)
                .addGap(21, 21, 21))
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(loginImage)
                .addGap(77, 77, 77))
        );

        panelCustom2.add(panelCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        FormRegister regist = new FormRegister();
        this.setVisible(false);
        regist.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String email = inputEmail.getText();
        char[] passwordArray = inputPassword.getPassword();
        
        String password = new String(passwordArray);
        
        try {
            Connection connection = connector.getConnection();
            String sql = "select * from users where email = ? AND password = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, email);
            statement.setString(2, password);
            
            ResultSet result =  statement.executeQuery();
            
            if(result.next()){
                userId = result.getString("id");
                System.out.println("id user baru login " + userId);
                JOptionPane.showMessageDialog(
                    this, 
                    "Login berhasil! Selamat datang, " + result.getString("username") + "!", 
                    "Login Berhasil", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                menuProfil profilPage = new menuProfil();
                Dashboard dashboardPage = new Dashboard();
                this.setVisible(false);
                dashboardPage.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(
                this, 
                "Email atau sandi Anda salah!", 
                "Login Gagal", 
                JOptionPane.ERROR_MESSAGE
            );
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
            this, 
            "Terjadi kesalahan: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void lb_showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showPasswordMouseClicked
        try {
            lb_showPassword.setVisible(false); // Sembunyikan ikon show
            lb_hidePassword.setVisible(true);  // Tampilkan ikon hide
            inputPassword.setEchoChar((char) 0); // Password terlihat
        } catch (Exception e) {
            System.out.println("Error saat menampilkan password: " + e.getMessage());
        }
    }//GEN-LAST:event_lb_showPasswordMouseClicked

    private void lb_hidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hidePasswordMouseClicked
        try {
            lb_showPassword.setVisible(true);  // Tampilkan ikon show
            lb_hidePassword.setVisible(false); // Sembunyikan ikon hide
            inputPassword.setEchoChar('*');    // Password disembunyikan
        } catch (Exception e) {
            System.out.println("Error saat menyembunyikan password: " + e.getMessage());
        }
    }//GEN-LAST:event_lb_hidePasswordMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel PasswordLabel;
    private Custom.JButtonRounded btnLogin;
    private Custom.JTextFieldRounded inputEmail;
    private Custom.JPasswordFieldRounded inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_hidePassword;
    private javax.swing.JLabel lb_showPassword;
    private javax.swing.JLabel loginDescription;
    private javax.swing.JLabel loginHeading;
    private javax.swing.JLabel loginImage;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom2;
    // End of variables declaration//GEN-END:variables
}
