/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Services.connector;
import com.mysql.cj.xdevapi.PreparableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author LOQ
 */
public class menuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public menuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardAgenda = new Custom.PanelCustom();
        lb_agenda = new javax.swing.JLabel();
        lb_jumlahAgenda = new javax.swing.JLabel();
        lb_iconAgenda = new javax.swing.JLabel();
        cardKategori = new Custom.PanelCustom();
        lb_kategori = new javax.swing.JLabel();
        lb_jumlahKategori = new javax.swing.JLabel();
        lb_iconKategori = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1095, 585));

        cardAgenda.setBackground(new java.awt.Color(253, 168, 104));
        cardAgenda.setPreferredSize(new java.awt.Dimension(200, 115));
        cardAgenda.setRoundBottomLeft(15);
        cardAgenda.setRoundBottomRight(15);
        cardAgenda.setRoundTopLeft(15);
        cardAgenda.setRoundTopRight(15);
        cardAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardAgendaMouseClicked(evt);
            }
        });

        lb_agenda.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        lb_agenda.setForeground(new java.awt.Color(0, 104, 153));
        lb_agenda.setText("AGENDA");

        lb_jumlahAgenda.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 36)); // NOI18N
        lb_jumlahAgenda.setForeground(new java.awt.Color(0, 104, 153));
        lb_jumlahAgenda.setText(getCountResultTask());

        lb_iconAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calendar-dashboard.png"))); // NOI18N
        lb_iconAgenda.setText("jLabel3");
        lb_iconAgenda.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout cardAgendaLayout = new javax.swing.GroupLayout(cardAgenda);
        cardAgenda.setLayout(cardAgendaLayout);
        cardAgendaLayout.setHorizontalGroup(
            cardAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAgendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahAgenda)
                    .addComponent(lb_agenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_iconAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        cardAgendaLayout.setVerticalGroup(
            cardAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAgendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_agenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_jumlahAgenda)
                .addGap(20, 20, 20))
            .addGroup(cardAgendaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_iconAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        cardKategori.setBackground(new java.awt.Color(253, 168, 104));
        cardKategori.setPreferredSize(new java.awt.Dimension(200, 115));
        cardKategori.setRoundBottomLeft(15);
        cardKategori.setRoundBottomRight(15);
        cardKategori.setRoundTopLeft(15);
        cardKategori.setRoundTopRight(15);

        lb_kategori.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        lb_kategori.setForeground(new java.awt.Color(0, 104, 153));
        lb_kategori.setText("KATEGORI");

        lb_jumlahKategori.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 36)); // NOI18N
        lb_jumlahKategori.setForeground(new java.awt.Color(0, 104, 153));
        lb_jumlahKategori.setText(getCountResultKategori());

        lb_iconKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/grid-dashboard.png"))); // NOI18N
        lb_iconKategori.setText("jLabel3");
        lb_iconKategori.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout cardKategoriLayout = new javax.swing.GroupLayout(cardKategori);
        cardKategori.setLayout(cardKategoriLayout);
        cardKategoriLayout.setHorizontalGroup(
            cardKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardKategoriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(cardKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahKategori)
                    .addComponent(lb_kategori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_iconKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        cardKategoriLayout.setVerticalGroup(
            cardKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardKategoriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_kategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_jumlahKategori)
                .addGap(20, 20, 20))
            .addGroup(cardKategoriLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_iconKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setPreferredSize(new java.awt.Dimension(167, 51));
        pn_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_mainMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-line (1) (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel3.setText("Dashboard");
        jLabel3.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mainLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cardAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cardKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 649, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(389, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private String getCountResultTask(){
        String total = "0";
        try{ 
            System.out.println("View.");
            Connection connection = connector.getConnection();
            String sql = "select count(*) as total from tasks where user_id = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, FormLogin.userId);
            ResultSet result =  statement.executeQuery();
            if(result.next()){
                total = result.getString("total");
                return total;
            }
            System.out.println("Kosong");
        } catch (Exception e) {
            System.out.println("Error saat menghitung jumlah task " + e.getMessage());
        }
        return total;
    }
    
    private String getCountResultKategori(){
        String total = "0";
        try{ 
            System.out.println("View.");
            Connection connection = connector.getConnection();
            String sql = "select count(*) as total from categories";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet result =  statement.executeQuery();
            if(result.next()){
                total = result.getString("total");
                return total;
            }
            System.out.println("Kosong");
        } catch (Exception e) {
            System.out.println("Error saat menghitung jumlah task " + e.getMessage());
        }
        return total;
    }
    private void pn_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseClicked

    private void pn_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseEntered

    private void pn_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseExited

    private void cardAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardAgendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cardAgendaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.PanelCustom cardAgenda;
    private Custom.PanelCustom cardKategori;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_agenda;
    private javax.swing.JLabel lb_iconAgenda;
    private javax.swing.JLabel lb_iconKategori;
    private javax.swing.JLabel lb_jumlahAgenda;
    private javax.swing.JLabel lb_jumlahKategori;
    private javax.swing.JLabel lb_kategori;
    private javax.swing.JPanel pn_main;
    // End of variables declaration//GEN-END:variables
}
