/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Custom.JButtonRounded;
import Services.connector;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LOQ
 */
public class menuKategori extends javax.swing.JPanel {

    public menuKategori() {
        initComponents();
        
        
        JButtonRounded button = new JButtonRounded();
        button.setFillOriginal(new Color(100, 100, 100));
        button.setFillOver(new Color(120, 120, 120));
        button.setFillClick(new Color(80, 80, 80));
        getAllCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoriesTable = new jtable_custom.JTable_Custom();
        jTextFieldRounded1 = new Custom.JTextFieldRounded();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonRoundedTambah1 = new Custom.JButtonRoundedTambah();
        jButtonRoundedHapus1 = new Custom.JButtonRoundedHapus();
        panelAdd = new javax.swing.JPanel();
        pn_main1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addCategoryName = new Custom.JTextFieldRounded();
        jLabel6 = new javax.swing.JLabel();
        addSimpanCategory = new Custom.JButtonRoundedTambah();
        jButtonRoundedKembali2 = new Custom.JButtonRoundedKembali();
        panelUpdate = new javax.swing.JPanel();
        pn_main2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldRounded5 = new Custom.JTextFieldRounded();
        jLabel14 = new javax.swing.JLabel();
        jButtonRoundedTambah4 = new Custom.JButtonRoundedTambah();
        jButtonRoundedKembali3 = new Custom.JButtonRoundedKembali();

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(1095, 585));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setPreferredSize(new java.awt.Dimension(1095, 620));

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setPreferredSize(new java.awt.Dimension(167, 51));
        pn_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_mainMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/grid-menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel3.setText("Data Kategori");
        jLabel3.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mainLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        categoriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Nama Kategori"
            }
        ));
        categoriesTable.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        categoriesTable.setShowGrid(true);
        jScrollPane1.setViewportView(categoriesTable);

        jTextFieldRounded1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldRounded1.setText("Cari");
        jTextFieldRounded1.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Kategori", "Prioritas", "Status" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/filter-funnel-01.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(24, 24));

        jButtonRoundedTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tambah-data.png"))); // NOI18N
        jButtonRoundedTambah1.setText("Tambah");
        jButtonRoundedTambah1.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedTambah1.setIconTextGap(10);
        jButtonRoundedTambah1.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedTambah1.setStrokeWidth(0);
        jButtonRoundedTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedTambah1ActionPerformed(evt);
            }
        });

        jButtonRoundedHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hapus-icon.png"))); // NOI18N
        jButtonRoundedHapus1.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedHapus1.setIconTextGap(10);
        jButtonRoundedHapus1.setLabel("Hapus");
        jButtonRoundedHapus1.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedHapus1.setStrokeWidth(0);
        jButtonRoundedHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedHapus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jButtonRoundedTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonRoundedHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRounded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRoundedTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRoundedHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card2");

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));
        panelAdd.setPreferredSize(new java.awt.Dimension(1095, 620));

        pn_main1.setBackground(new java.awt.Color(255, 255, 255));
        pn_main1.setPreferredSize(new java.awt.Dimension(251, 51));
        pn_main1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_main1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_main1MouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/grid-menu.png"))); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel5.setText("Tambah Data Kategori");
        jLabel5.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_main1Layout = new javax.swing.GroupLayout(pn_main1);
        pn_main1.setLayout(pn_main1Layout);
        pn_main1Layout.setHorizontalGroup(
            pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        pn_main1Layout.setVerticalGroup(
            pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        addCategoryName.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        addCategoryName.setPreferredSize(new java.awt.Dimension(1055, 36));
        addCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        jLabel6.setText("Nama Kategori");

        addSimpanCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save-01.png"))); // NOI18N
        addSimpanCategory.setText("Simpan");
        addSimpanCategory.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        addSimpanCategory.setIconTextGap(10);
        addSimpanCategory.setPreferredSize(new java.awt.Dimension(140, 40));
        addSimpanCategory.setStrokeWidth(0);
        addSimpanCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSimpanCategoryActionPerformed(evt);
            }
        });

        jButtonRoundedKembali2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out-04.png"))); // NOI18N
        jButtonRoundedKembali2.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedKembali2.setLabel("Kembali");
        jButtonRoundedKembali2.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedKembali2.setStrokeWidth(0);
        jButtonRoundedKembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedKembali2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addComponent(addSimpanCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonRoundedKembali2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pn_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRoundedKembali2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSimpanCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(addCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        panelMain.add(panelAdd, "card2");

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setPreferredSize(new java.awt.Dimension(1095, 620));

        pn_main2.setBackground(new java.awt.Color(255, 255, 255));
        pn_main2.setPreferredSize(new java.awt.Dimension(251, 51));
        pn_main2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_main2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_main2MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/grid-menu.png"))); // NOI18N
        jLabel12.setText("jLabel2");

        jLabel13.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel13.setText("Edit Data Kategori");
        jLabel13.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_main2Layout = new javax.swing.GroupLayout(pn_main2);
        pn_main2.setLayout(pn_main2Layout);
        pn_main2Layout.setHorizontalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        pn_main2Layout.setVerticalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jTextFieldRounded5.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jTextFieldRounded5.setPreferredSize(new java.awt.Dimension(1055, 36));
        jTextFieldRounded5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRounded5ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        jLabel14.setText("Nama Kategori");

        jButtonRoundedTambah4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save-01.png"))); // NOI18N
        jButtonRoundedTambah4.setText("Simpan");
        jButtonRoundedTambah4.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedTambah4.setIconTextGap(10);
        jButtonRoundedTambah4.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedTambah4.setStrokeWidth(0);
        jButtonRoundedTambah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedTambah4ActionPerformed(evt);
            }
        });

        jButtonRoundedKembali3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out-04.png"))); // NOI18N
        jButtonRoundedKembali3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedKembali3.setLabel("Kembali");
        jButtonRoundedKembali3.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedKembali3.setStrokeWidth(0);
        jButtonRoundedKembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedKembali3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(jButtonRoundedTambah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonRoundedKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRounded5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRoundedKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoundedTambah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(10, 10, 10)
                .addComponent(jTextFieldRounded5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        panelMain.add(panelUpdate, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pn_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseClicked

    private void pn_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseEntered

    private void pn_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseExited

    private void addCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCategoryNameActionPerformed

    private void pn_main1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main1MouseExited

    private void pn_main1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main1MouseEntered

    private void pn_main1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main1MouseClicked

    private void pn_main2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main2MouseClicked

    private void pn_main2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main2MouseEntered

    private void pn_main2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main2MouseExited

    private void jTextFieldRounded5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRounded5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRounded5ActionPerformed

    private void jButtonRoundedTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedTambah1ActionPerformed
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedTambah1ActionPerformed

    private void jButtonRoundedTambah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedTambah4ActionPerformed
        addCategory();
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedTambah4ActionPerformed

    private void jButtonRoundedKembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedKembali3ActionPerformed
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedKembali3ActionPerformed

    private void addSimpanCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSimpanCategoryActionPerformed
        addCategory();
        getAllCategories();
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_addSimpanCategoryActionPerformed

    private void jButtonRoundedKembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedKembali2ActionPerformed
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedKembali2ActionPerformed

    private void jButtonRoundedHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedHapus1ActionPerformed
        // TODO add your handling code here:
        int i = categoriesTable.getSelectedRow();
        if(i < 0){
            JOptionPane.showMessageDialog(this, "Pilih kategori yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Connection connection = connector.getConnection();
            String sql = "delete from categories where name = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, categoriesTable.getValueAt(i, 1).toString());
            
            statement.executeLargeUpdate();
            clearTable();
            getAllCategories();
            System.out.println("Behasil hapus");
        } catch (Exception e) {
            System.out.println("gagal hapus data category");
        }
    }//GEN-LAST:event_jButtonRoundedHapus1ActionPerformed

    public void clearTable(){
        for(int row=1; row < categoriesTable.getRowCount(); row++){
            for(int col=0; col < categoriesTable.getColumnCount(); col++){
                categoriesTable.setValueAt("", row, col);
            }
        }
    }
    public void addCategory(){
        System.out.println("View.menuKategori.addCategory()");
         try {
            Connection connection = connector.getConnection();
            String sql = "insert into categories value(?)";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1,addCategoryName.getText());
            
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Kategori berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
             System.out.println("Berhasil");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan kategori: ", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Gagal buat category "+ e.getMessage());
        }
    }
    
    public  void getAllCategories(){
        try {
            Connection connection = connector.getConnection();
            Statement statement = connection.createStatement();
            String sql = "select * from categories";
            ResultSet result = statement.executeQuery(sql);
            int i = 1;
            int row = 0;
            
            while(result.next()){
               
                categoriesTable.setValueAt(i,row , 0);
                categoriesTable.setValueAt(result.getString("name"),row , 1);
                 i++;   
                 row++;
                 
                 if(i == categoriesTable.getRowCount()){
                     categoriesTable.addRow(new Object[]{"",""});
                 }
            }
            
            System.out.println("Berhasil ambil semua categories");
        } catch (Exception e) {
            System.out.println("Gaga; ambil data categories");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.JTextFieldRounded addCategoryName;
    private Custom.JButtonRoundedTambah addSimpanCategory;
    private jtable_custom.JTable_Custom categoriesTable;
    private Custom.JButtonRoundedHapus jButtonRoundedHapus1;
    private Custom.JButtonRoundedKembali jButtonRoundedKembali2;
    private Custom.JButtonRoundedKembali jButtonRoundedKembali3;
    private Custom.JButtonRoundedTambah jButtonRoundedTambah1;
    private Custom.JButtonRoundedTambah jButtonRoundedTambah4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private Custom.JTextFieldRounded jTextFieldRounded1;
    private Custom.JTextFieldRounded jTextFieldRounded5;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelView;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_main1;
    private javax.swing.JPanel pn_main2;
    // End of variables declaration//GEN-END:variables
}
