/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Custom.JButtonRounded;
import Services.connector;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LOQ
 */
public class menuProfil extends javax.swing.JPanel {

    public menuProfil() {
        initComponents();
        
        
        JButtonRounded button = new JButtonRounded();
        button.setFillOriginal(new Color(100, 100, 100));
        button.setFillOver(new Color(120, 120, 120));
        button.setFillClick(new Color(80, 80, 80));
        
        getProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelCustom1 = new Custom.PanelCustom();
        jLabel7 = new javax.swing.JLabel();
        infoPassword = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        infoEmail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        infoUsername = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        infoFullname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButtonRoundedEdit1 = new Custom.JButtonRoundedEdit();
        panelUpdate = new javax.swing.JPanel();
        pn_main3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelCustom2 = new Custom.PanelCustom();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        inputFullname = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lb_showPassword = new javax.swing.JLabel();
        lb_hidePassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        btnSave = new Custom.JButtonRounded();
        jButtonRoundedKembali3 = new Custom.JButtonRoundedKembali();

        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(1095, 585));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));
        panelView.setPreferredSize(new java.awt.Dimension(1095, 620));

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setPreferredSize(new java.awt.Dimension(167, 51));
        pn_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_mainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_mainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_mainMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-circle.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel3.setText("Profil Anda");
        jLabel3.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mainLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelCustom1.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        jLabel7.setText("Informasi Pribadi");

        infoPassword.setEditable(false);
        infoPassword.setText("password");
        infoPassword.setPreferredSize(new java.awt.Dimension(1013, 40));

        jLabel22.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel22.setText("Password");

        infoEmail.setEditable(false);
        infoEmail.setPreferredSize(new java.awt.Dimension(1013, 40));
        infoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEmailActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel23.setText("Email");

        infoUsername.setEditable(false);
        infoUsername.setPreferredSize(new java.awt.Dimension(1013, 40));
        infoUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoUsernameActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel24.setText("Nama Pengguna");

        infoFullname.setEditable(false);
        infoFullname.setPreferredSize(new java.awt.Dimension(1013, 40));
        infoFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoFullnameActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel25.setText("Nama Lengkap");

        javax.swing.GroupLayout panelCustom1Layout = new javax.swing.GroupLayout(panelCustom1);
        panelCustom1.setLayout(panelCustom1Layout);
        panelCustom1Layout.setHorizontalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(infoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addComponent(infoUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addComponent(infoFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelCustom1Layout.setVerticalGroup(
            panelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustom1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(10, 10, 10)
                .addComponent(infoFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel24)
                .addGap(10, 10, 10)
                .addComponent(infoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addGap(10, 10, 10)
                .addComponent(infoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel22)
                .addGap(10, 10, 10)
                .addComponent(infoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonRoundedEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit-05.png"))); // NOI18N
        jButtonRoundedEdit1.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedEdit1.setIconTextGap(10);
        jButtonRoundedEdit1.setLabel("Edit");
        jButtonRoundedEdit1.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedEdit1.setStrokeWidth(0);
        jButtonRoundedEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedEdit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRoundedEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoundedEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card2");

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setPreferredSize(new java.awt.Dimension(1095, 620));

        pn_main3.setBackground(new java.awt.Color(255, 255, 255));
        pn_main3.setPreferredSize(new java.awt.Dimension(167, 51));
        pn_main3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_main3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_main3MouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-circle.png"))); // NOI18N
        jLabel15.setText("jLabel2");

        jLabel16.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 18)); // NOI18N
        jLabel16.setText("Profil Anda");
        jLabel16.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout pn_main3Layout = new javax.swing.GroupLayout(pn_main3);
        pn_main3.setLayout(pn_main3Layout);
        pn_main3Layout.setHorizontalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_main3Layout.setVerticalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        panelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        panelCustom2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelCustom2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        jLabel17.setText("Informasi Pribadi");
        panelCustom2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

        jLabel18.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel18.setText("Nama Lengkap");
        panelCustom2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, -1, -1));

        inputFullname.setPreferredSize(new java.awt.Dimension(1013, 40));
        inputFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFullnameActionPerformed(evt);
            }
        });
        panelCustom2.add(inputFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 86, -1, -1));

        inputUsername.setPreferredSize(new java.awt.Dimension(1013, 40));
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        panelCustom2.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 167, -1, -1));

        jLabel19.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel19.setText("Nama Pengguna");
        panelCustom2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 141, -1, -1));

        inputEmail.setPreferredSize(new java.awt.Dimension(1013, 40));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        panelCustom2.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 248, -1, -1));

        jLabel20.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel20.setText("Email");
        panelCustom2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 222, -1, -1));

        jLabel21.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 12)); // NOI18N
        jLabel21.setText("Password");
        panelCustom2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 303, -1, -1));

        lb_showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye.png"))); // NOI18N
        lb_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_showPasswordMouseClicked(evt);
            }
        });
        panelCustom2.add(lb_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 40, 40));

        lb_hidePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye-off (1).png"))); // NOI18N
        lb_hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hidePasswordMouseClicked(evt);
            }
        });
        panelCustom2.add(lb_hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 40, 40));

        inputPassword.setText("password");
        inputPassword.setPreferredSize(new java.awt.Dimension(1013, 40));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        panelCustom2.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 329, -1, -1));

        btnSave.setText("Simpan");
        btnSave.setFillClick(new java.awt.Color(42, 131, 192));
        btnSave.setFillOriginal(new java.awt.Color(51, 150, 217));
        btnSave.setFillOver(new java.awt.Color(81, 175, 239));
        btnSave.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnSave.setStrokeWidth(0);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelCustom2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 389, 1013, 40));

        jButtonRoundedKembali3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out-04.png"))); // NOI18N
        jButtonRoundedKembali3.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        jButtonRoundedKembali3.setLabel("Kembali");
        jButtonRoundedKembali3.setPreferredSize(new java.awt.Dimension(140, 40));
        jButtonRoundedKembali3.setStrokeWidth(0);
        jButtonRoundedKembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoundedKembali3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addComponent(pn_main3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRoundedKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRoundedKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelMain.add(panelUpdate, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pn_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseClicked

    private void pn_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseEntered

    private void pn_mainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_mainMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_mainMouseExited

    private void pn_main3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main3MouseClicked

    private void pn_main3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main3MouseEntered

    private void pn_main3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main3MouseExited

    private void inputFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFullnameActionPerformed

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void infoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoEmailActionPerformed

    private void infoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoUsernameActionPerformed

    private void infoFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoFullnameActionPerformed

    private void jButtonRoundedEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedEdit1ActionPerformed
        panelMain.removeAll();
        panelMain.add(panelUpdate);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedEdit1ActionPerformed

    private void jButtonRoundedKembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoundedKembali3ActionPerformed
        panelMain.removeAll();
        panelMain.add(panelView);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_jButtonRoundedKembali3ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updateProfile();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void lb_showPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_showPasswordMouseClicked
        try {
            lb_showPassword.setVisible(false); // Sembunyikan ikon show
            lb_hidePassword.setVisible(true);  // Tampilkan ikon hide
            inputPassword.setEchoChar((char) 0); // Password terlihat
        } catch (Exception e) {
            System.out.println("Error saat menampilkan password: " + e.getMessage());
        }
    }//GEN-LAST:event_lb_showPasswordMouseClicked

    private void lb_hidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hidePasswordMouseClicked
        try {
            lb_showPassword.setVisible(true);  // Tampilkan ikon show
            lb_hidePassword.setVisible(false); // Sembunyikan ikon hide
            inputPassword.setEchoChar('*');    // Password disembunyikan
        } catch (Exception e) {
            System.out.println("Error saat menyembunyikan password: " + e.getMessage());
        }
    }//GEN-LAST:event_lb_hidePasswordMouseClicked

    
    
    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void updateProfile(){
       String fullname = inputFullname.getText();
       String username = inputUsername.getText();
       String email = inputEmail.getText();
       String password = new String(inputPassword.getPassword());
       
        
        try {
            Connection connection = connector.getConnection();
            String sql = "update users set fullname = ?, username = ?, email = ?, password = ? where id = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, fullname);
            statement.setString(2, username);
            statement.setString(3, email);
            statement.setString(4, password);
            statement.setString(5, FormLogin.userId);
            int result = statement.executeUpdate();
            
            if(result > 0){
                JOptionPane.showMessageDialog(this, "Berhasil update data profil", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               
//                panelMain.removeAll();
//                panelMain.add(panelView);
//                panelMain.repaint();
//                panelMain.revalidate();
                getProfile();
            }
        } catch (Exception e) {
            System.out.println("View.menuProfil.updateProfile() " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Gagal mengupdate data profile", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void getProfile(){
        try {
            Connection connection = connector.getConnection();
            String sql = "select * from users where id = ?";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, FormLogin.userId);
            
            ResultSet result =  statement.executeQuery();
            
            if(result.next()){
                
                String fullname = result.getString("fullname");
                String username = result.getString("username");
                String email = result.getString("email");
                String password = result.getString("password");
                
                infoFullname.setText(fullname);
                inputFullname.setText(fullname);
                infoUsername.setText(username);
                inputUsername.setText(username);
                infoEmail.setText(email);
                inputEmail.setText(email);
                infoPassword.setText(password);
                inputPassword.setText(password);
            }
            
            
        } catch (Exception e) {
            System.out.println("Halo error ini errornya : " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.JButtonRounded btnSave;
    private javax.swing.JTextField infoEmail;
    private javax.swing.JTextField infoFullname;
    private javax.swing.JPasswordField infoPassword;
    private javax.swing.JTextField infoUsername;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputFullname;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private Custom.JButtonRoundedEdit jButtonRoundedEdit1;
    private Custom.JButtonRoundedKembali jButtonRoundedKembali3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb_hidePassword;
    private javax.swing.JLabel lb_showPassword;
    private Custom.PanelCustom panelCustom1;
    private Custom.PanelCustom panelCustom2;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelView;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_main3;
    // End of variables declaration//GEN-END:variables
}
